services:
    - docker

language: python

install:
  - git clone "https://github.com/TheCacophonyProject/cacophony-web"
  - cd cacophony-web
  - sed -i "25iRUN cd api && npm install typescript" Dockerfile
  - cd api
  - docker-compose build && docker-compose up --force-recreate
  - cd ../..
  - docker cp db-test-seed.sql cacophony-api:/db-seed.sql
  - pip install -r requirements.txt
before_script:
  - node ./cacophony-web/api/waitForApi.js || { docker ps; docker-compose logs; travis_terminate 1; }
  - sudo docker exec cacophony-api sh -c "sudo -i -u postgres psql cacophonytest -f/db-seed.sql"

script:
    - cd tests
    - pytest -s
