database: 'the-database-name'
s3_archive_auth: # Archive s3 can be used for cptv files
    endpoint_url: '<endpoint_url>'
    aws_access_key_id: '<access key>'
    aws_secret_access_key: '<secret access key>'
    bucket: objects
    db_bucket: database bucket



s3_auth: # Live s3 needs to be used for track data
    endpoint_url: '<endpoint_url>'
    aws_access_key_id: '<access key>'
    aws_secret_access_key: '<secret access key>'
    bucket: objects
